function(_recipe_opencl_system)
  find_package(OpenCL QUIET)

  if(TARGET OpenCL::OpenCL)
    get_target_property(_OPENCL_ALIASED OpenCL::OpenCL ALIASED_TARGET)
    if(_OPENCL_ALIASED)
      add_library(deps::opencl ALIAS ${_OPENCL_ALIASED})
    else()
      add_library(deps::opencl ALIAS OpenCL::OpenCL)
    endif()
    return()
  endif()

  cl_format_pkgconfig_req("OpenCL" "${CL_VERSION_REQ}" PKG_SPEC)
  find_package(PkgConfig QUIET)
  if(PkgConfig_FOUND)
    pkg_check_modules(opencl IMPORTED_TARGET GLOBAL ${PKG_SPEC})
  endif()
endfunction()
