function(_recipe_Qt5_system)
  if(NOT DEFINED Qt5_COMPONENTS)
    set(Qt5_COMPONENTS Core Gui Widgets)
  endif()

  if(CL_REQ_VERSION)
    find_package(Qt5 ${CL_REQ_VERSION} QUIET COMPONENTS ${Qt5_COMPONENTS})
  else()
    find_package(Qt5 QUIET COMPONENTS ${Qt5_COMPONENTS})
  endif()

  if(NOT Qt5_FOUND)
    return()
  endif()

  add_library(deps::Qt5 INTERFACE IMPORTED)
  foreach(_QT5_COMP ${Qt5_COMPONENTS})
    if(TARGET Qt5::${_QT5_COMP})
      target_link_libraries(deps::Qt5 INTERFACE Qt5::${_QT5_COMP})
    endif()
  endforeach()
endfunction()

function(_recipe_Qt5_package)
  if(CL_PACKAGE_MANAGER STREQUAL "apt")
    set(CL_PACKAGE_NAME "qtbase5-dev" PARENT_SCOPE)
  elseif(CL_PACKAGE_MANAGER STREQUAL "pacman")
    set(CL_PACKAGE_NAME "qt5-base" PARENT_SCOPE)
  elseif(CL_PACKAGE_MANAGER STREQUAL "brew")
    set(CL_PACKAGE_NAME "qt@5" PARENT_SCOPE)
  elseif(CL_PACKAGE_MANAGER STREQUAL "yum")
    set(CL_PACKAGE_NAME "qt5-qtbase-devel" PARENT_SCOPE)
  endif()
endfunction()
