function(_recipe_Qt6_system)
  if(NOT DEFINED Qt6_COMPONENTS)
    set(Qt6_COMPONENTS Core Gui Widgets)
  endif()

  if(CL_REQ_VERSION)
    find_package(Qt6 ${CL_REQ_VERSION} QUIET COMPONENTS ${Qt6_COMPONENTS})
  else()
    find_package(Qt6 QUIET COMPONENTS ${Qt6_COMPONENTS})
  endif()

  if(NOT Qt6_FOUND)
    return()
  endif()

  add_library(deps::Qt6 INTERFACE IMPORTED)
  foreach(_QT6_COMP ${Qt6_COMPONENTS})
    if(TARGET Qt6::${_QT6_COMP})
      target_link_libraries(deps::Qt6 INTERFACE Qt6::${_QT6_COMP})
    endif()
  endforeach()
endfunction()

function(_recipe_Qt6_package)
  if(CL_PACKAGE_MANAGER STREQUAL "apt")
    set(CL_PACKAGE_NAME "qt6-base-dev" PARENT_SCOPE)
  elseif(CL_PACKAGE_MANAGER STREQUAL "pacman")
    set(CL_PACKAGE_NAME "qt6-base" PARENT_SCOPE)
  elseif(CL_PACKAGE_MANAGER STREQUAL "brew")
    set(CL_PACKAGE_NAME "qt6" PARENT_SCOPE)
  elseif(CL_PACKAGE_MANAGER STREQUAL "yum")
    set(CL_PACKAGE_NAME "qt6-qtbase-devel" PARENT_SCOPE)
  endif()
endfunction()
