function(_recipe_sol2_system)
  find_package(sol2 CONFIG QUIET)
  if(TARGET sol2 OR TARGET sol2::sol2)
    return()
  endif()

  cl_format_pkgconfig_req("sol2" "${CL_VERSION_REQ}" PKG_SPEC)
  find_package(PkgConfig QUIET)
  if(PkgConfig_FOUND)
    pkg_check_modules(sol2 IMPORTED_TARGET GLOBAL ${PKG_SPEC})
  endif()
endfunction()

function(_recipe_sol2_source)
  cl_add_dep(lua)
  if(NOT TARGET deps::lua)
    _catalog_log(FATAL_ERROR "sol2: could not resolve a lua dependency")
  endif()

  set(SOL2_TAG "v3.5.0")
  if(CL_REQ_VERSION)
    set(SOL2_TAG "v${CL_REQ_VERSION}")
  endif()

  set(SOL2_URL "https://github.com/ThePhD/sol2/archive/refs/tags/${SOL2_TAG}.tar.gz")

  _catalog_get_cache_dir(SOL2_CACHE_DIR)
  string(SHA256 SOL2_HASH "${SOL2_URL}")
  string(SUBSTRING "${SOL2_HASH}" 0 12 SOL2_HASH_SHORT)
  set(SOL2_ARCHIVE "${SOL2_CACHE_DIR}/archive_${SOL2_HASH_SHORT}")
  set(SOL2_SRC_DIR "${SOL2_CACHE_DIR}/src_${SOL2_HASH_SHORT}")

  if(NOT EXISTS "${SOL2_ARCHIVE}")
    _catalog_download_file("${SOL2_URL}" "${SOL2_ARCHIVE}")
  endif()
  if(NOT EXISTS "${SOL2_SRC_DIR}")
    _catalog_extract_archive("${SOL2_ARCHIVE}" "${SOL2_SRC_DIR}")
  endif()

  file(GLOB SOL2_SUBDIRS "${SOL2_SRC_DIR}/*")
  list(LENGTH SOL2_SUBDIRS SOL2_SUBDIR_COUNT)
  if(SOL2_SUBDIR_COUNT EQUAL 1)
    list(GET SOL2_SUBDIRS 0 SOL2_SUBDIR)
    if(IS_DIRECTORY "${SOL2_SUBDIR}")
      set(SOL2_SRC_DIR "${SOL2_SUBDIR}")
    endif()
  endif()

  if(NOT EXISTS "${SOL2_SRC_DIR}/include/sol/sol.hpp")
    _catalog_log(FATAL_ERROR "sol2: expected headers not found under ${SOL2_SRC_DIR}/include")
  endif()

  add_library(sol2 INTERFACE)
  target_include_directories(sol2 INTERFACE $<BUILD_INTERFACE:${SOL2_SRC_DIR}/include>)
  target_link_libraries(sol2 INTERFACE deps::lua)
  target_compile_definitions(sol2 INTERFACE SOL_ALL_SAFETIES_ON=1)
  target_compile_features(sol2 INTERFACE cxx_std_17)
endfunction()
