function(_recipe_sqlite3_system)
  if(NOT CMAKE_CROSSCOMPILING)
    # CMake ships a built-in FindSQLite3 module.
    if(CL_REQ_VERSION)
      find_package(SQLite3 ${CL_REQ_VERSION} QUIET)
    else()
      find_package(SQLite3 QUIET)
    endif()

    set(_SQLITE3_PICK "")
    if(TARGET SQLite3::SQLite3)
      set(_SQLITE3_PICK SQLite3::SQLite3)
    elseif(TARGET SQLite::SQLite3)
      set(_SQLITE3_PICK SQLite::SQLite3)
    endif()
    if(_SQLITE3_PICK)
      get_target_property(_SQLITE3_ALIASED ${_SQLITE3_PICK} ALIASED_TARGET)
      if(_SQLITE3_ALIASED)
        add_library(deps::sqlite3 ALIAS ${_SQLITE3_ALIASED})
      else()
        add_library(deps::sqlite3 ALIAS ${_SQLITE3_PICK})
      endif()
      return()
    endif()
  endif()

  cl_format_pkgconfig_req("sqlite3" "${CL_VERSION_REQ}" PKG_SPEC)
  find_package(PkgConfig QUIET)
  if(PkgConfig_FOUND)
    if(CL_STATIC)
      pkg_check_modules(sqlite3 IMPORTED_TARGET GLOBAL "--static" ${PKG_SPEC})
    else()
      pkg_check_modules(sqlite3 IMPORTED_TARGET GLOBAL ${PKG_SPEC})
    endif()
  endif()
endfunction()

function(_recipe_sqlite3_package)
  if(CL_REQUIRE_STATIC) # Most package managers don't provide static libs.
    return()
  endif()

  if(CL_PACKAGE_MANAGER STREQUAL "apt")
    set(CL_PACKAGE_NAME "libsqlite3-dev" PARENT_SCOPE)
  elseif(CL_PACKAGE_MANAGER STREQUAL "pacman")
    set(CL_PACKAGE_NAME "sqlite" PARENT_SCOPE)
  elseif(CL_PACKAGE_MANAGER STREQUAL "brew")
    set(CL_PACKAGE_NAME "sqlite" PARENT_SCOPE)
  elseif(CL_PACKAGE_MANAGER STREQUAL "yum")
    set(CL_PACKAGE_NAME "sqlite-devel" PARENT_SCOPE)
  elseif(CL_PACKAGE_MANAGER STREQUAL "apk")
    set(CL_PACKAGE_NAME "sqlite-dev" PARENT_SCOPE)
  endif()
endfunction()

function(_recipe_sqlite3_source)
  cl_import_source(
    NAME sqlite3
    DOWNLOAD_ONLY
    URL https://www.sqlite.org/2026/sqlite-amalgamation-3530400.zip
  )

  if(NOT EXISTS "${CL_SOURCE_DIR}/sqlite3.c")
    _catalog_log(FATAL_ERROR "sqlite3: amalgamation source not found under ${CL_SOURCE_DIR}")
  endif()

  set(SQLITE3_LIB_TYPE STATIC)
  if(CL_REQ_TYPE STREQUAL "SHARED" OR CL_REQ_TYPE STREQUAL "PREFER_SHARED")
    set(SQLITE3_LIB_TYPE SHARED)
  endif()

  add_library(sqlite3 ${SQLITE3_LIB_TYPE} "${CL_SOURCE_DIR}/sqlite3.c")
  target_include_directories(sqlite3 PUBLIC $<BUILD_INTERFACE:${CL_SOURCE_DIR}>)
  target_compile_definitions(sqlite3 PRIVATE SQLITE_ENABLE_FTS5 SQLITE_ENABLE_RTREE SQLITE_ENABLE_JSON1)
  if(UNIX)
    target_link_libraries(sqlite3 PRIVATE m pthread)
    find_library(SQLITE3_DL_LIBRARY dl)
    if(SQLITE3_DL_LIBRARY)
      target_link_libraries(sqlite3 PRIVATE ${SQLITE3_DL_LIBRARY})
    endif()
  endif()
endfunction()
