function(_recipe_zlib_system)
  if(NOT CMAKE_CROSSCOMPILING)
    if(CL_REQ_VERSION)
      find_package(ZLIB ${CL_REQ_VERSION} QUIET)
    else()
      find_package(ZLIB QUIET)
    endif()

    if(TARGET ZLIB::ZLIB)
      add_library(deps::zlib ALIAS ZLIB::ZLIB)
      return()
    endif()
  endif()

  cl_format_pkgconfig_req("zlib" "${CL_VERSION_REQ}" PKG_SPEC)
  find_package(PkgConfig QUIET)
  if(PkgConfig_FOUND)
    if(CL_STATIC)
      pkg_check_modules(zlib IMPORTED_TARGET GLOBAL "--static" ${PKG_SPEC})
    else()
      pkg_check_modules(zlib IMPORTED_TARGET GLOBAL ${PKG_SPEC})
    endif()
  endif()
endfunction()

function(_recipe_zlib_package)
  if(CL_REQUIRE_STATIC) # Most package managers don't provide static libs.
    return()
  endif()

  if(CL_PACKAGE_MANAGER STREQUAL "apt")
    set(CL_PACKAGE_NAME "zlib1g-dev" PARENT_SCOPE)
  elseif(CL_PACKAGE_MANAGER STREQUAL "pacman")
    set(CL_PACKAGE_NAME "zlib" PARENT_SCOPE)
  elseif(CL_PACKAGE_MANAGER STREQUAL "brew")
    set(CL_PACKAGE_NAME "zlib" PARENT_SCOPE)
  elseif(CL_PACKAGE_MANAGER STREQUAL "yum")
    set(CL_PACKAGE_NAME "zlib-devel" PARENT_SCOPE)
  elseif(CL_PACKAGE_MANAGER STREQUAL "apk")
    set(CL_PACKAGE_NAME "zlib-dev" PARENT_SCOPE)
  elseif(CL_PACKAGE_MANAGER STREQUAL "zypper")
    set(CL_PACKAGE_NAME "zlib-devel" PARENT_SCOPE)
  endif()
endfunction()

function(_recipe_zlib_source)
  set(ZLIB_TAG "v1.3.2")
  if(CL_REQ_VERSION)
    set(ZLIB_TAG "v${CL_REQ_VERSION}")
  endif()

  cl_import_source(
    NAME zlib
    URL https://github.com/madler/zlib/archive/refs/tags/${ZLIB_TAG}.tar.gz
  )

  set(_ZLIB_PICK "")
  if(CL_STATIC AND TARGET ZLIB::ZLIBSTATIC)
    set(_ZLIB_PICK ZLIB::ZLIBSTATIC)
  elseif(TARGET ZLIB::ZLIB)
    set(_ZLIB_PICK ZLIB::ZLIB)
  elseif(TARGET ZLIB::ZLIBSTATIC)
    set(_ZLIB_PICK ZLIB::ZLIBSTATIC)
  endif()
  if(_ZLIB_PICK)
    get_target_property(_ZLIB_ALIASED ${_ZLIB_PICK} ALIASED_TARGET)
    if(_ZLIB_ALIASED)
      add_library(deps::zlib ALIAS ${_ZLIB_ALIASED})
    else()
      add_library(deps::zlib ALIAS ${_ZLIB_PICK})
    endif()
  endif()
endfunction()
